//vscode extension: humao.rest-client
// just click "send request" above each URL

// in the case of JWTs, login with a user and copy paste response JWT
// JWTs are valid for an hour (subject to change) so you don't need to constantly login

POST http://localhost:8080/Users/register
Content-Type: application/json

{
    "Email" : "salt5@gmail.com",
    "Password" : "salt5",
    "FirstName" : "first",
    "LastName" : "last",
    "Admin": false
}

###
// (this is associated with a valid account)
POST http://localhost:8080/Users/login
Content-Type: application/json

{
    "Email": "salt5@gmail.com",
    "Password": "salt5"
}

###

POST http://localhost:8080/JWT/verify
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQ1QGdtYWlsLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE3MjE5OTU2LCJleHAiOjE2MTcyMjM1NTZ9.vkxvxkyOs9l6ECgQPU5lFGmVZDQYg8XrvKkunqb4SHk"
}

###

POST http://localhost:8080/JWT/refresh
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQ1QGdtYWlsLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE3MjE5OTU2LCJleHAiOjE2MTcyMjM1NTZ9.vkxvxkyOs9l6ECgQPU5lFGmVZDQYg8XrvKkunqb4SHk"
}
